# Created with GitHubActions version 0.3.8
name: CI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  - pull_request
  - push
jobs:
  linux:
    name: Test on Ubuntu (Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - '1.13.4'
          - '1.14.5'
          - '1.15.8'
          - '1.16.3'
          - '1.17.3'
          - '1.18.4'
          - '1.19.0'
        otp:
          - '24.3'
          - '25.3'
          - '26.2'
          - '27.3'
          - '28.1'
        exclude:
          - elixir: '1.13.4'
            otp: '26.2'
          - elixir: '1.13.4'
            otp: '27.3'
          - elixir: '1.13.4'
            otp: '28.1'
          - elixir: '1.14.5'
            otp: '27.3'
          - elixir: '1.14.5'
            otp: '28.1'
          - elixir: '1.15.8'
            otp: '27.3'
          - elixir: '1.15.8'
            otp: '28.1'
          - elixir: '1.16.3'
            otp: '27.3'
          - elixir: '1.16.3'
            otp: '28.1'
          - elixir: '1.17.3'
            otp: '24.3'
          - elixir: '1.17.3'
            otp: '28.1'
          - elixir: '1.18.4'
            otp: '24.3'
          - elixir: '1.19.0'
            otp: '24.3'
          - elixir: '1.19.0'
            otp: '25.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Elixir
        id: setup-beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore deps
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-X-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ steps.setup-beam.outputs.setup-beam-version }}
      - name: Restore _build
        uses: actions/cache@v4
        with:
          path: _build
          key: _build-X-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ steps.setup-beam.outputs.setup-beam-version }}
      - name: Restore test/support/plts
        if: ${{ matrix.elixir == '1.19.0' && matrix.otp == '28.1' }}
        uses: actions/cache@v4
        with:
          path: test/support/plts
          key: test/support/plts-X-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ steps.setup-beam.outputs.setup-beam-version }}
      - name: Get dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: MIX_ENV=test mix deps.compile
      - name: Compile project
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Check unused dependencies
        if: ${{ matrix.elixir == '1.19.0' && matrix.otp == '28.1' }}
        run: mix deps.unlock --check-unused
      - name: Check code format
        if: ${{ matrix.elixir == '1.19.0' && matrix.otp == '28.1' }}
        run: mix format --check-formatted
      - name: Lint code
        if: ${{ matrix.elixir == '1.19.0' && matrix.otp == '28.1' }}
        run: mix credo --strict
      - name: Run tests
        if: ${{ !(matrix.elixir == '1.19.0' && matrix.otp == '28.1') }}
        run: mix test
      - name: Run tests with coverage
        if: ${{ matrix.elixir == '1.19.0' && matrix.otp == '28.1' }}
        run: mix coveralls.github
      - name: Static code analysis
        if: ${{ matrix.elixir == '1.19.0' && matrix.otp == '28.1' }}
        run: mix dialyzer --format github --force-check
